### PR TITLE
Vpsadev 146

### PR DESCRIPTION
**Pull request by sherakama**

### CODE REVIEW

**Comment by sherakama** [comment]
Added author exposed filter and view row counter to manage content view

**Comment by sherakama** [comment]
@cynmij,

Please to review.

**Comment by cynmij** [comment]
screen shot 2015-09-10 at 4 04 33 pm

Do we need all these VBO actions?

**Comment by sherakama** [comment]
Im not sure but those where in there before this pull request. We can create a new ticket to remove them if they prove to be an issue. 

Thanks for the review.

**Pull request merged**
