### PR TITLE
7.x-3.0-alpha1

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Stable release for composer

# Needed By (Date)
- Before we can push socorro live.

# Urgency
- 3/10

# Steps to Test

1. Review code
2. Merge
3. Release tag following Drupal version practices
4. Release tag following Semantic version practices
5. Push commit rolling back module versions to `-dev`

# Associated Issues and/or People
- SITES-533
- SITES-642

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jbickar** [comment]
@sherakama is there an upgrade path on this? (for the release notes)

**Review by jbickar — APPROVED** [review]

**Comment by sherakama** [comment]
No, that is why it is alpha.
I'm not even sure it is possible to go from 2.x to 3.x as it is such a major change.

**Comment by sherakama** [comment]
https://stanfordits.atlassian.net/browse/SITES-660

**Comment by jbickar** [comment]
So we need a tagged release on `7.x-2.x` also.

**Pull request merged**
